const fs = require('fs');
const https = require('https');
const path = require('path');

const OUTPUT_FILE = path.join(__dirname, 'jhatsapp', 'src', 'data', 'conversations.js');

// Helper to fetch data
function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'RSC': '1', 'User-Agent': 'Mozilla/5.0' } }, (res) => {
      let data = '';
      res.on('data', (c) => data += c);
      res.on('end', () => resolve(data));
      res.on('error', reject);
    }).on('error', reject);
  });
}

// Format Name from Slug
function formatName(slug) {
  return slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

async function run() {
  console.log("Step 1: Fetching all Jmail profiles from Sitemap...");
  const sitemapData = await fetchUrl('https://jmail.world/sitemap/0.xml');
  const slugRegex = /<loc>https:\/\/jmail\.world\/person\/([^<]+)<\/loc>/g;
  
  const slugs = [];
  for (const match of sitemapData.matchAll(slugRegex)) {
    // Ignore aliases or generic lists if necessary, but we'll try to get all
    if (!match[1].includes('alias')) {
      slugs.push(match[1]);
    }
  }

  // To avoid hitting API limits or taking hours, we will process all of them one by one.
  console.log(`Found ${slugs.length} profiles. Step 2: Fetching threads for each person...`);
  
  const allContacts = [];
  const allConversations = {};
  const pinnedContacts = [];

  // Limit to first 20 for now to prevent memory bloat, user can increase this.
  const limit = Math.min(slugs.length, 25);
  for (let i = 0; i < limit; i++) {
    const slug = slugs[i];
    console.log(`[${i+1}/${limit}] Fetching data for ${slug}...`);
    
    const data = await fetchUrl(`https://jmail.world/person/${slug}`);
    
    const threadRegex = /\{"doc_id":"([^"]+)",(?:.*?)?(?:,"count":(\d+))?,(?:.*?)?"subject":"([^"]*)",(?:.*?)?"latest_sender_name":"([^"]*)",(?:.*?)?"latest_sender_email":"([^"]*)",(?:.*?)?"formatted_date":"([^"]*)",(?:.*?)?"preview":"([^"]*)"(?:.*?)?\}/g;

    const parsedThreads = [];
    for (const match of data.matchAll(threadRegex)) {
      parsedThreads.push({
        doc_id: match[1],
        sender_name: match[4],
        sender_email: match[5],
        formatted_date: match[6],
        preview: match[7]
      });
    }

    // Deduplicate
    const unique = [];
    const seen = new Set();
    for (const t of parsedThreads) {
      if (!seen.has(t.doc_id)) {
        seen.add(t.doc_id);
        unique.push(t);
      }
    }
    
    // Sort
    unique.sort((a, b) => new Date(a.formatted_date) - new Date(b.formatted_date));

    if (unique.length === 0) continue; // Skip if no threads

    const messages = [];
    let idCounter = 1;

    for (const t of unique) {
      let from = "them";
      const name = (t.sender_name || "").toLowerCase();
      const email = (t.sender_email || "").toLowerCase();
      
      // Determine if from Jeffrey Epstein
      if (name.includes("jeffrey") || email.includes("jeffrey") || name.includes("epstein") || email.includes("epstein") || email.includes("jeevacation")) {
        from = "me";
      }

      const dateObj = new Date(t.formatted_date);
      const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
      const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
      const formattedDate = `${days[dateObj.getDay()]}, ${months[dateObj.getMonth()]} ${dateObj.getDate()}, ${dateObj.getFullYear()}`;
      
      messages.push({
        id: idCounter++,
        from: from,
        text: t.preview,
        time: "12:00 PM",
        date: formattedDate
      });
    }

    const lastMessage = messages[messages.length - 1];
    let lastDate = "";
    if (lastMessage) {
      const d = new Date(unique[unique.length - 1].formatted_date);
      lastDate = `${(d.getMonth()+1).toString().padStart(2,'0')}/${d.getDate().toString().padStart(2,'0')}/${d.getFullYear().toString().slice(2)}`;
    }

    const contactName = formatName(slug);
    allContacts.push({
      id: slug,
      name: contactName,
      role: "Jmail Contact",
      avatar: `https://jmail.world/_next/image?url=%2Fpeople-thumbnails%2F${slug}.png&w=256&q=75`
    });

    if (i < 10) pinnedContacts.push(slug);

    allConversations[slug] = {
      contactId: slug,
      lastDate: lastDate,
      lastMessage: lastMessage ? lastMessage.text : "",
      messages: messages
    };
  }

  console.log("Step 3: Compiling data and saving to conversations.js...");

  let fileContent = `// Auto-generated by JhatsApp Sync Script
export const contacts = ${JSON.stringify(allContacts, null, 2)};

export const pinnedContacts = ${JSON.stringify(pinnedContacts, null, 2)};

export const conversations = ${JSON.stringify(allConversations, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log("✅ Successfully synced all Jmail data to the website!");
}

run();
